# -*- coding: utf-8 -*-
"""src/preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128VRYbLRKtElfsUPLyvAo9ZRhqvoZd9R
"""

from sklearn.preprocessing import LabelEncoder, StandardScaler

def preprocess_data(csv_path):
    df = pd.read_csv(csv_path)

    # Drop leakage columns
    df.drop(columns=[
        'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
        'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'
    ], inplace=True)

    # Encode target
    df['Attrition_Flag'] = df['Attrition_Flag'].map({
        'Existing Customer': 0,
        'Attrited Customer': 1
    })

    # Encode categorical features
    cat_cols = df.select_dtypes(include='object').columns
    le = LabelEncoder()
    for col in cat_cols:
        df[col] = le.fit_transform(df[col])

    # Features & target
    X = df.drop(columns=['Attrition_Flag', 'CLIENTNUM'])
    y = df['Attrition_Flag']

    # Scale features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    return X_scaled, y

