# -*- coding: utf-8 -*-
"""src/train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128VRYbLRKtElfsUPLyvAo9ZRhqvoZd9R
"""

from preprocess import preprocess_data
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
import joblib

def train_and_save_model():
    X, y = preprocess_data("data/BankChurners.csv")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Handle imbalance
    smote = SMOTE(random_state=42)
    X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

    # Train model
    model = XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
        eval_metric="logloss"
    )

    model.fit(X_train_smote, y_train_smote)

    # Save model
    joblib.dump(model, "model/xgb_churn_model.pkl")

    print("Model trained and saved successfully.")

if __name__ == "__main__":
    train_and_save_model()

