# -*- coding: utf-8 -*-
"""src/predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128VRYbLRKtElfsUPLyvAo9ZRhqvoZd9R
"""

import joblib
import numpy as np

def predict_churn(input_features):
    model = joblib.load("model/xgb_churn_model.pkl")

    input_array = np.array(input_features).reshape(1, -1)
    prediction = model.predict(input_array)

    return "Churn" if prediction[0] == 1 else "Not Churn"

# Example usage
if __name__ == "__main__":
    sample_customer = [45, 1, 3, 2, 1, 4, 39, 2, 1500, 8000, 12000]
    print(predict_churn(sample_customer))

